### ISSUE TITLE
Result not good

### ISSUE THREAD

**Issue by zhangbaijin** [mevah/ExPGAN#9]
Hello, thank you very much for your work. From your results, it seems that the effect is not so good. Do you have a better picture of the test effect?

**Comment by mevah** [comment]
Hi @zhangbaijin, thanks for your input. This was for a class project thus we could not train the model such longer and get results that are far better than the state of the art, and we do not claim that. Below you can see a comparison:
![Screenshot 2020-04-15 at 09 53 35](https://user-images.githubusercontent.com/19671562/79312319-042c6500-7eff-11ea-8dbd-bf41dce757e4.png)
![Screenshot 2020-04-15 at 09 52 40](https://user-images.githubusercontent.com/19671562/79312325-055d9200-7eff-11ea-8e21-731ab2cedef6.png)

**Comment by zhangbaijin** [comment]
OK,Thanks a lot, i will try it
